name: React App

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the app
      run: |
        npm run build

    - name: Upload build artifact (optional)
      uses: actions/upload-artifact@v2
      with:
        name: react-build
        path: build/
